export let TYPES = {
  IConfigController: Symbol.for("IConfigController"),
  IConfigServer: Symbol.for("IConfigServer"),
  IConfigStore: Symbol.for("IConfigStore"),
  IConnectionContextManager: Symbol.for("IConnectionContextManager"),
  ICoreServer: Symbol.for("ICoreServer"),
  ICypressFacade: Symbol.for("ICypressFacade"),
  IDebugLogger: Symbol.for("IDebugLogger"),
  IExpressServerFacade: Symbol.for("IExpressServerFacade"),
  IHttpMitmProxyFacade: Symbol.for("IHttpMitmProxyFacade"),
  IMain: Symbol.for("IMain"),
  INegotiateManager: Symbol.for("INegotiateManager"),
  INtlm: Symbol.for("INtlm"),
  INtlmManager: Symbol.for("INtlmManager"),
  IExternalNtlmProxyFacade: Symbol.for("IExternalNtlmProxyFacade"),
  INtlmProxyMitm: Symbol.for("INtlmProxyMitm"),
  INtlmProxyServer: Symbol.for("INtlmProxyServer"),
  IStartup: Symbol.for("IStartup"),
  IUpstreamProxyConfigurator: Symbol.for("IUpstreamProxyConfigurator"),
  IUpstreamProxyManager: Symbol.for("IUpstreamProxyManager"),
  NewableIWinSsoFacade: Symbol.for("Newable<IWinSsoFacade>"),
  NewableIConnectionContext: Symbol.for("Newable<IConnectionContext>"),
};
