name: Unit-test

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  unit-test:
    name: Unit test
    # env:
    #  DEBUG: "express*,cypress:plugin:ntlm-auth*,win-sso"
    #  DEBUG_NTLM_HEADERS: '1'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [14.13.1, 14, 15, 16.0.0, 16, 17, 18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run unittest
        env:
          CI: true
